@startuml
node "External client" {
  [eg. Postman, curl...]
}

node "WebClient Service" {
  HTTP - [WebClient]
  [eg. Postman, curl...] --> HTTP
}

node "Wiremock cloud"{
   HTTPS - [Mocked http server]
   [WebClient] --> HTTPS
}

@enduml